name: Deploy Migrations to Supabase

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify migration files
        run: |
          echo "Listing migration files:"
          ls -la supabase/migrations/
          echo "Migration file contents:"
          cat supabase/migrations/*.sql

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link and push migrations
        run: |
          echo "Linking project..."
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
          echo "Pushing migrations..."
          supabase db push -d
