name: Deploy Migrations to Supabase

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: djtunsxmzhxffehkclre
      DATABASE_URL: postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD }}@db.djtunsxmzhxffehkclre.supabase.co:5432/postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: |
          echo "Linking project..."
          supabase link --project-ref "$SUPABASE_PROJECT_ID" --db-url "$DATABASE_URL" --debug

      - name: Push migrations
        run: |
          echo "Pushing migrations..."
          supabase db push --debug
